#!/bin/sh
export NVM_DIR=/home/git/.nvm
. $NVM_DIR/nvm.sh
if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPOSITORY_BASENAME=$(basename "$PWD" .git) 
  else
    REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
  fi

while read oldrev newrev refname
do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
  case $branch in
  master)
    appname=$REPOSITORY_BASENAME
    ;;
  develop)
    appname=${REPOSITORY_BASENAME}_dev
    ;;
  esac
  cd ~/apps/$appname
  unset GIT_DIR
  git pull
  npm install --production
  npm prune --production
  pm2 restart $appname -m
done
