#!/bin/sh
export NVM_DIR=/home/git/.nvm
. $NVM_DIR/nvm.sh
if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPOSITORY_BASENAME=$(basename "$PWD" .git) 
  else
    REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
  fi
echo repository: $REPOSITORY_BASENAME

while read oldrev newrev refname
do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
  echo branch: $branch
  case $branch in
  master)
    appname=$REPOSITORY_BASENAME
    ;;
  develop)
    appname=${REPOSITORY_BASENAME}_dev
    ;;
  esac
  pm2 pull $appname
done
