#!/bin/sh

# List changed files
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_file() {
        echo "$changed_files" | grep --quiet "$1" && eval "$2"
}
check_file "package.json" "npm install && npm prune"
