#!/bin/sh
export NVM_DIR=/home/git/.nvm
. $NVM_DIR/nvm.sh
if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPOSITORY_BASENAME=$(basename "$PWD" .git) 
  else
    REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
  fi
pm2 stop $REPOSITORY_BASENAME -m
