env:
  es6: true
  commonjs: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 6
rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
