server:
  port: 3000
  host: localhost
db:
  host: localhost
  database: wbt-framework
jwt:
  options:
    expiresIn: 7d
    subject: authenticate
download:
  cwd: ./
  dest: .tmp
assets:
  serve: true
  root: /dist
  title: WBT Framework
  base: wbt-framework
  versions:
    angular: 1.4.7
    bootstrap: 3.3.5
    fontAwesome: 4.4.0
    lodash: 3.10.1
    restangular: 1.5.1
logging: true