server:
  port: 3000
  host: localhost
db:
  host: localhost
  database: MyDatabase
jwt:
  options:
    expiresIn: 7d
    subject: authenticate
download:
  cwd: ./
  dest: .tmp
assets:
  serve: true
  root: ./dist
  index: index.html
logging: true