server:
  port: 3000
  host: localhost
db:
  host: localhost
  database: wbt-framework
jwt:
  options:
    expiresIn: 7d
    subject: authenticate
assets:
  serve: true
  root: /dist
  title: WBT Framework
  base: wbt-framework
  versions:
    angular: 1.4.8
    bootstrap: 3.3.6
    fontAwesome: 4.4.0
    jquery: 2.1.4
    lodash: 3.10.1
    restangular: 1.5.1
logging: true
mail:
  transport: nodemailer-stub-transport
  jwt:
    subject: mail
    expiresIn: 1h
  defaults:
    from: wbt-framework@iim.de
  templates:
    verify: |
      Hallo ${data.user.profile.nickname},
      
      bitte bestätige deine E-Mail-Adresse, indem du auf den folgenden Link klickst:
      
      ${data.token}