server:
  port: 3000
  host: localhost
db:
  host: localhost
  database: MyDatabase
jwt:
  options:
    expiresInMinutes: 60*24*7
    subject: authenticate
download:
  cwd: ./
  dest: .tmp
assets:
  serve: true
  root: ./dist
  index: index
logging: true