- _id: home
  title: WBT-Framework
  menu: WBT-Framework
  icon: home
  active: true
- _id: content
  title: Inhalte
  menu: Inhalte
  icon: book
  active: true
- _id: download
  title: Download
  menu: Download
  icon: download
  active: true
- _id: author
  title: Autorenmodus
  menu: Autorenmodus
  icon: pencil
  active: true
- _id: contact
  title: Kontakt
  menu: Kontakt
  icon: support
  active: true
- _id: impressum
  title: Impressum
  menu: Impressum
  active: true