swagger: '2.0'
info:
  title: WBT-API
  description: |
    Verarbeitet AJAX-Requests vom Frontend, liefert Inhalte aus, regelt Benutzeranmeldung, überwacht Benutzeraktivitäten
  version: '1.0'
  contact:
    name: Tamara Cook
    email: tamara.cook@psychol.uni-giessen.de
basePath: /api
consumes:
  - application/json
produces:
  - application/json
  - text/html
  - text/plain
paths:
  /comments:
    post:
      summary: Create a new comment
      parameters:
        - name: comment
          in: body
          schema: {$ref: '#/definitions/Comment'}
      responses:
        200: {$ref: '#/responses/ok'}
  /meta:
    get:
      summary: Get list of meta items
      parameters:
        - $ref: '#/parameters/conditions'
        - $ref: '#/parameters/projections'
        - $ref: '#/parameters/options'
      responses:
        200:
          description: A list of meta items
          schema:
            type: array
            items: {$ref: '#/definitions/Meta'}
    post:
      parameters:
        - name: meta
          in: body
          required: true
          schema: {$ref: '#/definitions/Meta'}
          description: A meta item to create
      responses:
        200: {$ref: '#/responses/ok'}
        400: {$ref: '#/responses/illegalInput'}
        401: {$ref: '#/responses/unauthenticated'}
        403: {$ref: '#/responses/forbidden'}
        500: {$ref: '#/responses/generalError'}
  /meta/{_id}:
    parameters:
      - name: _id
        type: string
        in: path
        required: true
        description: A meta item _id, which is a string
    get:
      summary: Get a meta item based on its _id
      responses:
        200:
          description: A complete meta item
          schema: {$ref: '#/definitions/Meta'}
        404: {$ref: '#/responses/notFound'}
    patch:
      summary: Update a meta item based on its _id
      parameters:
        - {$ref: '#/parameters/patches'}
      responses:
        200: {$ref: '#/responses/ok'}
        400: {$ref: '#/responses/illegalInput'}
        401: {$ref: '#/responses/unauthenticated'}
        403: {$ref: '#/responses/forbidden'}
        404: {$ref: '#/responses/notFound'}
        500: {$ref: '#/responses/generalError'}
    delete:
      summary: Remove a meta item based on its _id
      responses:
        200: {$ref: '#/responses/ok'}
        400: {$ref: '#/responses/illegalInput'}
        401: {$ref: '#/responses/unauthenticated'}
        403: {$ref: '#/responses/forbidden'}
        404: {$ref: '#/responses/notFound'}
        500: {$ref: '#/responses/generalError'}
  /units:
    get:
      summary: Get list of units
      parameters:
        - {$ref: '#/parameters/conditions'}
        - {$ref: '#/parameters/projections'}
        - {$ref: '#/parameters/options'}
      responses:
        200:
          description: A list of unit documents
          schema:
            type: array
            items: {$ref: '#/definitions/Unit'}
    post:
      description: Create a new unit
      parameters:
        - name: unit
          in: body
          required: true
          description: A new unit document to store
          schema: {$ref: '#/definitions/Unit'}
      responses:
        200:
          description: The newly created unit document
          schema: {$ref: '#/definitions/Unit'}
  /units/{_id}:
    parameters:
      - {$ref: '#/parameters/_id'}
    get:
      summary: Get a unit based on its _id
      responses:
        200:
          description: A unit document
          schema: {$ref: '#/definitions/Unit'}
    patch:
      summary: Update a unit based on its _id
      parameters:
        - {$ref: '#/parameters/patches'}
      responses:
        200: {$ref: '#/responses/ok'}
    delete:
      summary: Remove a unit based on its _id
      responses:
        200: {$ref: '#/responses/ok'}
  /users:
    head:
      summary: Check if a user exists
      parameters:
        - name: email
          description: The email to check for existence
          in: query
          required: true
          type: string
      responses:
        200: {$ref: '#/responses/ok'}
        404: {$ref: '#/responses/notFound'}
    post:
      summary: Register a new user
      parameters:
        - name: user
          in: body
          required: true
          description: A new user document to store
          schema: {$ref: '#/definitions/User'}
      responses:
        200: {$ref: '#/responses/ok'}
  /users/{_id}:
    parameters:
      - {$ref: '#/parameters/_id'}
    get:
      summary: Get user data by its _id
      responses:
        200:
          description: A user document
          schema: {$ref: '#/definitions/User'}
    patch:
      summary: Update a user's data based on its _id
      parameters:
        - {$ref: '#/parameters/patches'}
      responses:
        200: {$ref: '#/responses/ok'}
    delete:
      summary: Remove a user based on its _id
      responses:
        200: {$ref: '#/responses/ok'}
  /users/{_id}/emails/{type}:
    parameters:
      - {$ref: '#/parameters/_id'}
      - name: type
        description: Email type
        required: true
        type: string
        in: path
    get:
      summary: Send email to user by ID and type
      responses:
        200: {$ref: '#/responses/ok'}
  /users/{_id}/password:
    parameters:
      - {$ref: '#/parameters/_id'}
    put:
      summary: Change the user's password
      parameters:
        - name: data
          description: old and new password
          in: body
          schema:
            type: object
            required:
              - old
              - new
            properties:
              old: {type: string}
              new: {type: string}
            description: An object with current and new password
      responses:
        200: {$ref: '#/responses/ok'}
  /subjects:
    get:
      summary: Get a list of subjects
      parameters:
        - name: search
          description: a string to search for
          in: query
          type: string
      responses:
        200:
          description: A list of subject documents
          schema:
            type: array
            items: {$ref: '#/definitions/Subject'}
  /watches:
    post:
      summary: create a new watch item
      parameters:
        - name: message
          in: body
          required: true
          schema: {$ref: '#/definitions/Watch'}
      responses:
        200: {$ref: '#/responses/ok'}
definitions:
  ObjectId:
    type: string
    pattern: /^[0-9a-fA-F]{24}$/
  Watch:
    type: object
    required:
      - _id
      - state
      - time
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      time: {type: number}
      state: {type: string}
      videoid: {type: string}
      list: {type: string}
      listType:
        type: string
        enum:
          - playlist
          - search
          - user
  File:
    type: object
    description: A mongodb gridfs file object
    required:
      - _id
      - length
      - chunkSize
      - uploadDate
      - md5
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      length: {type: number}
      chunkSize: {type: number}
      uploadDate:
        type: string
        format: date
      md5: {type: string}
      filename: {type: string}
      contentType: {type: string}
      aliases:
        type: array
        items: {type: string}
      metadata: {type: object}
  Subject:
    type: object
    description: A subject document
    required:
      - _id
      - group
      - name
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      group: {type: string}
      name: {type: string}
  User:
    type: object
    description: A user document
    required:
      - _id
      - email
      - role
      - profile
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      email: {type: string}
      role:
        type: string
        enum:
          - user
          - author
      password: {type: string}
      profile:
        type: object
        required:
          - age
          - sex
          - subject
        properties:
          nickname: {type: string}
          age: {type: integer}
          sex:
            type: string
            enum:
              - male
              - female
          subject: {type: string}
          reasons:
            type: array
            items:
              type: string
              enum:
                - interesse
                - langeweile
                - klausur
                - author
      akzeptanz:
        type: object
        required:
          - comments
          - ratings
        properties:
          ratings:
            type: array
            items: {$ref: '#/definitions/ObjectId'}
          comments:
            type: array
            items: {$ref: '#/definitions/ObjectId'}
      views:
        type: array
        items: {$ref: '#/definitions/ObjectId'}
      done:
        type: array
        items: {$ref: '#/definitions/ObjectId'}
  Meta:
    type: object
    required:
      - _id
      - title
      - position
      - menu
      - active
    properties:
      _id:
        type: string
        enum:
          - home
          - content
          - download
          - author
          - contact
          - impressum
      title: {type: string}
      icon: {type: string}
      position: {type: integer}
      menu: {type: string}
      active: {type: boolean}
      body: {type: string}
  PatchDocuments:
    type: array
    items: {$ref: '#/definitions/PatchDocument'}
  PatchDocument:
    type: object
    description: A JSONPatch document as defined by RFC 6902
    required:
      - op
      - path
    properties:
      op:
        type: string
        description: The operation to be performed
        enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
      path:
        type: string
        description: A JSON-Pointer
      value:
        type: object
        description: The value to be used within the operations.
      from:
        type: string
        description: A string containing a JSON Pointer value.
  Unit:
    type: object
    description: A unit document
    required:
      - _id
      - title
      - description
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      title: {type: string}
      subtitle: {type: string}
      position: {type: integer}
      description: {type: string}
      requires:
        type: array
        items: {$ref: '#/definitions/ObjectId'}
      topics:
        type: array
        items: {$ref: '#/definitions/Topic'}
      views:
        type: array
        items: {$ref: '#/definitions/ObjectId'}
      akzeptanz:
        type: object
        required:
          - comments
          - ratings
        properties:
          comments:
            type: array
            items: {$ref: '#/definitions/ObjectId'}
          ratings:
            type: array
            items: {$ref: '#/definitions/ObjectId'}
  Topic:
    type: object
    required:
      - _id
      - title
      - body
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      title: {type: string}
      subtitle: {type: string}
      body: {type: string}
      examples:
        type: array
        items: {$ref: '#/definitions/Example'}
      extras:
        type: array
        items: {$ref: '#/definitions/Extra'}
  Example:
    type: object
    required:
      - _id
      - title
      - body
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      title: {type: string}
      subtitle: {type: string}
      body: {type: string}
  Extra:
    type: object
    required:
      - _id
      - title
      - body
    properties:
      _id: {$ref: '#/definitions/ObjectId'}
      title: {type: string}
      subtitle: {type: string}
      body: {type: string}
  Comment:
    type: object
    required:
      - unit
      - user
      - value
    properties:
      unit: {$ref: '#/definitions/ObjectId'}
      user: {$ref: '#/definitions/ObjectId'}
      value: {type: string}
parameters:
  _id:
    name: _id
    type: string
    in: path
    required: true
    description: Mongodb _id
  conditions:
    name: conditions
    in: query
    type: string
    required: false
    description: Item filtering for mongoose
  projections:
    name: projections
    in: query
    type: string
    required: false
    description: Field filtering for mongoose
  options:
    name: options
    in: query
    type: string
    required: false
    default: sort=position
    description: Options for mongoose
  patches:
    name: patches
    in: body
    required: true
    description: An array of JSON patch documents
    schema: {$ref: '#/definitions/PatchDocuments'}
responses:
  ok:
    description: Success
  illegalInput:
    description: Some parameter was incorrect
  unauthenticated:
    description: Action only allowed for authenticated users
  forbidden:
    description: Action not allowed for this user
  notFound:
    description: Requested item(s) not found
  generalError:
    description: Any internal server error
securityDefinitions:
  basic:
    type: basic
    description: Login with email and password, fetch a JWT token
  jwt:
    type: apiKey
    description: JWT Authentication
    in: header
    name: Authorization
security:
  - jwt: []
  - basic: []
